global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using SmartWorkz.Core.Shared.Results;
global using ClosedXML.Excel;
global using iTextSharp.text;
global using iTextSharp.text.pdf;
