namespace SmartWorkz.Core.Shared.Response;

/// <summary>
/// Implements RFC 7807 Problem Details for HTTP APIs standard response format.
/// Provides a standardized way to represent error details in API responses.
/// </summary>
public sealed class ProblemDetailsResponse
{
    /// <summary>
    /// A URI reference (RFC 3986) that identifies the problem type.
    /// Encourages deferred resolution of problem causes.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server.
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// Provides a way to correlate error reports with server logs.
    /// </summary>
    public string? Instance { get; set; }

    /// <summary>
    /// A dictionary of additional properties defined by the problem type.
    /// Extensions allow custom problem details beyond the RFC 7807 spec.
    /// </summary>
    public Dictionary<string, object> Extensions { get; set; } = new();

    /// <summary>
    /// Factory method for 400 Bad Request error with validation details.
    /// </summary>
    public static ProblemDetailsResponse ValidationError(string detail, string instance, Dictionary<string, object>? extensions = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.1",
            Title = "One or more validation errors occurred.",
            Status = 400,
            Detail = detail,
            Instance = instance,
            Extensions = extensions ?? new()
        };
    }

    /// <summary>
    /// Factory method for 401 Unauthorized error.
    /// </summary>
    public static ProblemDetailsResponse Unauthorized(string detail = "Authentication is required", string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7235#section-3.1",
            Title = "Unauthorized",
            Status = 401,
            Detail = detail,
            Instance = instance
        };
    }

    /// <summary>
    /// Factory method for 403 Forbidden error.
    /// </summary>
    public static ProblemDetailsResponse Forbidden(string detail = "You do not have permission to access this resource", string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.3",
            Title = "Forbidden",
            Status = 403,
            Detail = detail,
            Instance = instance
        };
    }

    /// <summary>
    /// Factory method for 404 Not Found error.
    /// </summary>
    public static ProblemDetailsResponse NotFound(string detail = "The requested resource was not found", string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.4",
            Title = "Not Found",
            Status = 404,
            Detail = detail,
            Instance = instance
        };
    }

    /// <summary>
    /// Factory method for 409 Conflict error.
    /// </summary>
    public static ProblemDetailsResponse Conflict(string detail = "The request conflicts with the current state of the server", string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.5.8",
            Title = "Conflict",
            Status = 409,
            Detail = detail,
            Instance = instance
        };
    }

    /// <summary>
    /// Factory method for 500 Internal Server Error.
    /// </summary>
    public static ProblemDetailsResponse InternalServerError(string detail = "An internal server error occurred", string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = "https://tools.ietf.org/html/rfc7231#section-6.6.1",
            Title = "Internal Server Error",
            Status = 500,
            Detail = detail,
            Instance = instance
        };
    }

    /// <summary>
    /// Factory method for custom problem details.
    /// </summary>
    public static ProblemDetailsResponse Custom(string? type, string title, int status, string? detail = null, string? instance = null)
    {
        return new ProblemDetailsResponse
        {
            Type = type,
            Title = title,
            Status = status,
            Detail = detail,
            Instance = instance
        };
    }
}
